---
- name: Install and configure nginx
  hosts: web
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: Install nginx package
      apt:
        name: "{{ nginx_package }}"
        state: present
        update_cache: yes
      notify:
        - Enable nginx service
        - Restart nginx

    - name: Configure nginx
      template:
        src: templates/nginx.conf.j2
        dest: "{{ nginx_conf_path }}"
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart nginx

  handlers:
    - name: Enable nginx service
      systemd:
        name: "{{ nginx_service }}"
        enabled: yes

    - name: Restart nginx
      systemd:
        name: "{{ nginx_service }}"
        state: restarted